# For replicaset all the meta data field of the pod will move inside spec
apiVersion: apps/v1 #for replicaset make sure its apps/v1
kind: ReplicaSet   #Replicaset kind
metadata:
  name: webapp-api       #Name of the ReplicaSet
spec:
  selector:           #it will manage all the pods where label matches key value pair app:webapp-api
    matchLabels:
      app: webapp-api
  replicas: 2         #Number of replicas of the pod
  template:           #Template for the pod to be created by the ReplicaSet
    metadata:         #Metadata for the pod template
      labels:         #Labels for the pod template
        app: webapp-api   #Key-value pair for the label of the pod template

    spec:             #Specification for the pod template
      containers:     #Containers to be created in the pod
        - name: webapp-api          #Name of the container
          image: shubhamdixit863/goapibackendwithrds  #Docker image for the container
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: webapp-api-service
spec:
  #This defines which pods are going to be represented by this service
  # the service becomes a network endpoint for either or other services
  # or maybe external users to connect to eg browser
  selector:
    app: webapp-api   # the pod label we want to create service for


  ports:
    - name: http #just a label
      port: 80   #internal port of the cluster in which pod is running
      targetPort: 8080   # only be user when type is NodePort should be greater than 30000

  type: LoadBalancer