name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses:  actions/checkout@v3
        name: "Checkout the repo"
      - name: "Run Unit Tests"
        run: make test

  build:
    needs: test # this will ensure that build runs only when the test passes
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set Image Tag
        run: echo "IMAGE_TAG"=$(date +%s) >> $GITHUB_ENV
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag shubhamdixit863/goapibackendbeta:${{env.IMAGE_TAG}}
      - name: Login To Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push the Image to Docker Hub
        run: docker push shubhamdixit863/goapibackendbeta:${{env.IMAGE_TAG}}


  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
      - test
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - uses: actions/checkout@v2
      - name: Run kubectl
        uses: nikosch86/github-action-eks-kubectl@main
        with:
          command: "apply deployment.yaml"
        env:
          EKS_CLUSTER: cluster-eksCluster-d8da1b5